### ISSUE TITLE
API to handler decoder?

### ISSUE THREAD

**Issue by proyb6** [wI2L/jettison#1]
Jsoniter is a drop in replacement for JSON, I thought you could post a benchmark there if you like to showcase more efficient JSON.

https://github.com/kostya/benchmarks

**Comment by wI2L** [comment]
Hello. I am not sure to fully understand what you mean, but jettison does not feature a JSON decoder, and I have no plans about adding one, since there is already many great alternatives to `encoding/json` out there.

**Comment by proyb6** [comment]
Yup, I have wrote that benchmark with Jsoniter. Can be closed in this issue.
